<?php

/**
 * @file
 * CiviCRM Token main module file.
 */

/**
 * Implements hook_token_info().
 */
function civicrm_token_token_info() {
  $info = [];
  $info['types']['civi'] = array(
    'name' => t('CiviCRM'),
    'description' => t('Tokens related to CiviCRM.'),
  );
  $info['tokens']['civi']['contact_ID'] = array(
    'name' => t('Contact ID'),
    'description' => t('CiviCRM contact ID of current user.'),
  );
  $info['tokens']['civi']['contact_dashboard'] = array(
    'name' => t('Contact Dashboard'),
    'description' => t('CiviCRM contact dashborad of current user.'),
  );
  $info['tokens']['civi']['contact_first_name'] = array(
    'name' => t('Contact First Name'),
    'description' => t('CiviCRM contact first name of current user.'),
  );
  $info['tokens']['civi']['contact_last_name'] = array(
    'name' => t('Contact Last Name'),
    'description' => t('CiviCRM contact last name of current user.'),
  );
  $info['tokens']['civi']['contact_email'] = array(
    'name' => t('Contact Email'),
    'description' => t('CiviCRM contact email of current user.'),
  );
  $info['tokens']['civi']['contact_telephone'] = array(
    'name' => t('Contact Phone Number'),
    'description' => t('CiviCRM contact telephone number of current user.'),
  );
  return $info;
}

/**
 * Implements hook_tokens().
 *
 */
function civicrm_token_tokens($type, $tokens, array $data = [], array $options = []) {
  $replacements = array();

  $currentUser = \Drupal::currentUser();
  $sanitize = !empty($options['sanitize']);

  \Drupal::service('civicrm')->initialize();
  $currentUserContactId = \CRM_Core_BAO_UFMatch::getContactId($currentUser->id());

  if ($type == 'civi' && !is_null($currentUserContactId)) {
    $result = civicrm_api3('Contact', 'get', array('id' => $currentUserContactId));
    if( $result['count'] !== 0 || $result['is_error'] == 0 ){
      $params = array_pop($result['values']);
      $replacements['[civi:contact_ID]'] = $currentUserContactId;
      $replacements['[civi:contact_dashboard]'] = "civicrm/user?reset=1&id=" . $currentUserContactId;
      $replacements['[civi:contact_first_name]'] = $params['first_name'];
      $replacements['[civi:contact_last_name]'] = $params['last_name'];
      $replacements['[civi:contact_email]'] = $params['email'];
      $replacements['[civi:contact_telephone]'] = $params['phone'];
    }
  }
  return $replacements;
}
